import type { TicketTemplate, TemplateToken } from "@/lib/template-types"
import { DEFAULT_TICKET_SIZE_MM } from "@/lib/units"

export const DEFAULT_TOKENS: TemplateToken[] = [
  { key: "ticketId", label: "Ticket ID" },
  { key: "taskId", label: "Task ID" },
  { key: "taskName", label: "Task" },
  { key: "company", label: "Company" },
  { key: "trade", label: "Trade" },
  { key: "date", label: "Date" },
  { key: "status", label: "Status" },
  { key: "description", label: "Description" },
  { key: "area.level1", label: "Area L1" },
  { key: "area.level2", label: "Area L2" },
  { key: "area.level3", label: "Area L3" },
  { key: "area.level4", label: "Area L4" },
  { key: "area.level5", label: "Area L5" },
]

// Derived from rasterization of Karten_Layout_Blank.pdf (A4, 2x2 tickets).
// Coordinates are in mm relative to the ticket top-left.
export const DEFAULT_TEMPLATE: TicketTemplate = {
  id: "default",
  name: "Default (Karten Layout)",
  widthMm: DEFAULT_TICKET_SIZE_MM.width,
  heightMm: DEFAULT_TICKET_SIZE_MM.height,
  elements: [
    {
      id: "border",
      name: "Outer border",
      type: "rect",
      xMm: 0,
      yMm: 0,
      wMm: DEFAULT_TICKET_SIZE_MM.width,
      hMm: DEFAULT_TICKET_SIZE_MM.height,
      stroke: "#111111",
      strokeWidthMm: 0.4,
      fill: "transparent",
      locked: true,
    },
    {
      id: "inner-border",
      name: "Inner border",
      type: "rect",
      xMm: 4.49,
      yMm: 4.32,
      wMm: 61.04,
      hMm: 114.47,
      stroke: "#111111",
      strokeWidthMm: 0.4,
      fill: "transparent",
      locked: true,
    },
    {
      id: "header-divider",
      name: "Header divider",
      type: "line",
      x1Mm: 4.49,
      y1Mm: 41.66,
      x2Mm: 65.53,
      y2Mm: 41.66,
      stroke: "#111111",
      strokeWidthMm: 0.5,
      locked: true,
    },
    {
      id: "notes-divider",
      name: "Notes divider",
      type: "line",
      x1Mm: 4.49,
      y1Mm: 73.15,
      x2Mm: 65.53,
      y2Mm: 73.15,
      stroke: "#111111",
      strokeWidthMm: 0.5,
      locked: true,
    },
    {
      id: "side-strip",
      name: "Side strip",
      type: "rect",
      xMm: 4.74,
      yMm: 4.49,
      wMm: 7.11,
      hMm: 36.83,
      fill: "#cbbfd7",
      stroke: "transparent",
      locked: true,
    },
    {
      id: "notes-bar",
      name: "Notes bar",
      type: "rect",
      xMm: 4.83,
      yMm: 41.99,
      wMm: 60.36,
      hMm: 5.51,
      fill: "#d8d8d8",
      stroke: "transparent",
      locked: true,
    },
    {
      id: "notes-bar-bottom",
      name: "Notes bar bottom line",
      type: "line",
      x1Mm: 4.49,
      y1Mm: 47.67,
      x2Mm: 65.53,
      y2Mm: 47.67,
      stroke: "#111111",
      strokeWidthMm: 0.4,
      locked: true,
    },
    {
      id: "bottom-fill",
      name: "Bottom fill",
      type: "rect",
      xMm: 4.49,
      yMm: 73.32,
      wMm: 61.04,
      hMm: 45.47,
      fill: "#9dbb61",
      stroke: "transparent",
      locked: true,
    },
    {
      id: "bottom-notch",
      name: "Bottom notch",
      type: "rect",
      xMm: 4.49,
      yMm: 106.43,
      wMm: 34.46,
      hMm: 12.36,
      fill: "#ffffff",
      stroke: "transparent",
      locked: true,
    },
    {
      id: "bottom-triangle",
      name: "Bottom triangle",
      type: "triangle",
      xMm: 45.64,
      yMm: 90.0,
      wMm: 19.89,
      hMm: 28.79,
      corner: "br",
      fill: "#cbbfd7",
      stroke: "transparent",
      locked: true,
    },
    {
      id: "notes-label",
      name: "Notes label",
      type: "text",
      xMm: 5.5,
      yMm: 42.6,
      wMm: 30,
      hMm: 4,
      text: "Anmerkungen:",
      fontSizeMm: 3.6,
      fontWeight: 600,
      color: "#111111",
      align: "left",
      valign: "middle",
      locked: true,
    },
    {
      id: "task-name",
      name: "Task name",
      type: "text",
      xMm: 13.2,
      yMm: 8.4,
      wMm: 51,
      hMm: 12,
      text: "{{taskName}}",
      fontSizeMm: 5.2,
      fontWeight: 600,
      color: "#111111",
      align: "left",
      valign: "top",
    },
    {
      id: "task-id",
      name: "Task ID",
      type: "text",
      xMm: 13.2,
      yMm: 22.6,
      wMm: 51,
      hMm: 6,
      text: "ID: {{taskId}}",
      fontSizeMm: 3.6,
      fontWeight: 500,
      color: "#111111",
      align: "left",
      valign: "top",
    },
    {
      id: "date",
      name: "Date",
      type: "text",
      xMm: 13.2,
      yMm: 30.2,
      wMm: 51,
      hMm: 5,
      text: "{{date}}",
      fontSizeMm: 3.4,
      fontWeight: 500,
      color: "#111111",
      align: "left",
      valign: "top",
    },
    {
      id: "strip-text",
      name: "Company / Trade",
      type: "text",
      xMm: 5.0,
      yMm: 6.0,
      wMm: 6.5,
      hMm: 34,
      text: "{{company}}\n{{trade}}",
      fontSizeMm: 3.0,
      fontWeight: 600,
      color: "#111111",
      align: "center",
      valign: "middle",
      writingMode: "vertical-rl",
    },
  ],
}
